## In this tutorial, you will discover how to create your first deep learning neural network model in Python using Keras.

**The steps you are going to cover in this tutorial are as follows**
1. Load Data.
2. Define Keras Model.
3. Compile Keras Model.
4. Fit Keras Model.
5. Evaluate Keras Model.
6. Tie It All Together.
7. Make Predictions

### 1. Load Data

In [1]:
# first neural network with keras tutorial
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

In [2]:
# load the dataset
dataset = loadtxt('pima_indians_diabetes.csv', delimiter=',')
dataset[2]

array([  8.   , 183.   ,  64.   ,   0.   ,   0.   ,  23.3  ,   0.672,
        32.   ,   1.   ])

In [3]:
# split data into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]

In [4]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [5]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

### 2. Define Keras Model and add layers

In [6]:
# define the keras model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))  # 1st hidden layer
model.add(Dense(8, activation='relu'))  # 2nd hidden layer
model.add(Dense(1, activation='sigmoid'))  # outout layer

### COmpile Keras model

In [7]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

### 4. Fit Keras Model

In [8]:
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10, verbose=1)

Epoch 1/150
77/77 [==============================] - 0s 1ms/step - loss: 2.9160 - accuracy: 0.4622
Epoch 2/150
77/77 [==============================] - 0s 1ms/step - loss: 1.1850 - accuracy: 0.5469
Epoch 3/150
77/77 [==============================] - 0s 1ms/step - loss: 0.8274 - accuracy: 0.6250
Epoch 4/150
77/77 [==============================] - 0s 998us/step - loss: 0.7197 - accuracy: 0.6445
Epoch 5/150
77/77 [==============================] - 0s 1ms/step - loss: 0.6669 - accuracy: 0.6484
Epoch 6/150
77/77 [==============================] - 0s 1ms/step - loss: 0.6395 - accuracy: 0.6732
Epoch 7/150
77/77 [==============================] - 0s 1ms/step - loss: 0.6274 - accuracy: 0.6680
Epoch 8/150
77/77 [==============================] - 0s 1ms/step - loss: 0.6189 - accuracy: 0.6771
Epoch 9/150
77/77 [==============================] - 0s 1ms/step - loss: 0.6170 - accuracy: 0.6719
Epoch 10/150
77/77 [==============================] - 0s 1ms/step - loss: 0.6211 - accuracy: 0.6589
Epoch 1

77/77 [==============================] - 0s 1ms/step - loss: 0.5531 - accuracy: 0.7109
Epoch 83/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5503 - accuracy: 0.7070
Epoch 84/150
77/77 [==============================] - 0s 931us/step - loss: 0.5504 - accuracy: 0.7057
Epoch 85/150
77/77 [==============================] - 0s 895us/step - loss: 0.5525 - accuracy: 0.7201
Epoch 86/150
77/77 [==============================] - 0s 905us/step - loss: 0.5537 - accuracy: 0.7083
Epoch 87/150
77/77 [==============================] - 0s 869us/step - loss: 0.5549 - accuracy: 0.7070
Epoch 88/150
77/77 [==============================] - 0s 948us/step - loss: 0.5506 - accuracy: 0.7044
Epoch 89/150
77/77 [==============================] - 0s 903us/step - loss: 0.5465 - accuracy: 0.7083
Epoch 90/150
77/77 [==============================] - 0s 967us/step - loss: 0.5534 - accuracy: 0.7148
Epoch 91/150
77/77 [==============================] - 0s 931us/step - loss: 0.5495 - accuracy: 0.70

### 5. Evaluate Keras Model

In [9]:
# evaluate the keras model
_,accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

24/24 [==============================] - 0s 1ms/step - loss: 0.5260 - accuracy: 0.7161
Accuracy: 71.61


### 6. Tie it all together
**Combining all the code together - Let's skip this step since this is a step-by-step tutorial**

### 7. Make Predictions

In [10]:
# make class predictions with the model
predictions = model.predict_classes(X)
predictions

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
    

In [11]:
for i in range(7):
    print('%s => predicted %d, (actual %d)' % (X[i].tolist(), predictions[i], y[i]))

[6.0, 148.0, 72.0, 35.0, 0.0, 33.6, 0.627, 50.0] => predicted 1, (actual 1)
[1.0, 85.0, 66.0, 29.0, 0.0, 26.6, 0.351, 31.0] => predicted 0, (actual 0)
[8.0, 183.0, 64.0, 0.0, 0.0, 23.3, 0.672, 32.0] => predicted 1, (actual 1)
[1.0, 89.0, 66.0, 23.0, 94.0, 28.1, 0.167, 21.0] => predicted 0, (actual 0)
[0.0, 137.0, 40.0, 35.0, 168.0, 43.1, 2.288, 33.0] => predicted 0, (actual 1)
[5.0, 116.0, 74.0, 0.0, 0.0, 25.6, 0.201, 30.0] => predicted 0, (actual 0)
[3.0, 78.0, 50.0, 32.0, 88.0, 31.0, 0.248, 26.0] => predicted 0, (actual 1)
